version: 2

models:
  - name: customer_new
    description: dynamic table 
    config:
      
      access: private 
      contract: {enforced = true}
    
    columns:
      - name: first_name 
        constraints:
          - type: not_null 
            warn_unenforced: true
        data_tests:
          - not_null
  


    


